[[bots]]
channel = "##horsing-around" # The channel this bot will support
format = "json" # Bot format (text, json, pickle)
path = "bots/##horsing-around" # Path to the chain/corpus to load
language = "italian" # We use this to filter stopwords & other language specific tweaks.
